#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S2,     IR,             sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S3,     DEPTH,          sensorSONAR)
#pragma config(Motor,  mtr_S1_C1_1,     motorA,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     motorB,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorC,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_1,     motorD,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     motorF,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C4_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*--------------------------------------------------------------------------------------------------------*\
|*                                                                                                        *|
|*                                    - Tetrix Simple Tank Drive -                                        *|
|*                                          ROBOTC on Tetrix                                              *|
|*                                                                                                        *|
|*  This program allows you to drive a robot via remote control using the ROBOTC Debugger.                *|
|*  This particular method uses "Tank Drive" where each side is controlled individually like a tank.      *|
|*                                                                                                        *|
|*                                        ROBOT CONFIGURATION                                             *|
|*    NOTES:                                                                                              *|
|*                                                                                                        *|
|*    MOTORS & SENSORS:                                                                                   *|
|*    [I/O Port]              [Name]              [Type]              [Description]                       *|
|*    Port D                  motorD              12V                 Right motor                         *|
|*    Port E                  motorE              12V                 Left motor                          *|
\*---------------------------------------------------------------------------------------------------4246-*/

#include "JoystickDriver.c"
int movex, movey;
int threshold = 40;
int movement[10];
bool movefoward;
int guess = 0;
int guesscount = 0;
task main()
{
	movement[0] = -1;
	movement[1] = -100;
	movement[2] = -75;
	movement[3] = -50;
	movement[4] = -25;
	movement[5] = 0;
	movement[6] = 25;
	movement[7] = 50;
	movement[8] = 75;
	movement[9] = 100;
  while(true)
  {
  	//Discover movex
    movex = SensorValue[IR];
    movey = SensorValue[DEPTH];
    nxtDisplayString(0, "%d", movex);
    if (movey <= 50 && movex == 5 && guess == 2) {//change value to 70
    		motor[motorA] = 0;
 				motor[motorB] = 0;
 				motor[motorC] = 0;
 				motor[motorD] = 0;
 				continue;
    	}
    	if (movey >= 50 && movex == 0 && guess == 2) {
    		guess = 0;
    		movefoward = false;
    	}
    if (guess == 1 && movex != 0) {
    	guess = 2;
    	motor[motorA] = 0;
 				motor[motorB] = 0;
 				motor[motorC] = 0;
 				motor[motorD] = 0;
    }
    if (!movefoward) { //look at it
    	if (movex == 0) {
    			if (guesscount > 1000 && guess == 0) {
    				guess = 1;
    				motor[motorA] = -50;
   					motor[motorD] = -50;
   					motor[motorC] = 60;
   					motor[motorB] = -50;
   			}
   			guesscount++;
   			continue;
    	}
    	nxtDisplayString(0, "%d", movey);

   		if (movex != 5) {
   			motor[motorA] = -movement[movex];
   			motor[motorD] = -movement[movex];
   			motor[motorC] = -movement[movex] + 10;
   			motor[motorB] = -movement[movex];
 			}
 			else {
 				motor[motorA] = 0;
 				motor[motorB] = 0;
 				motor[motorC] = 0;
 				motor[motorD] = 0;
 				movefoward = true;
 			}
 		}
 		else { //Go towards it
 			nxtDisplayString(0, "GO TOWARDS IT!");
 			if (movex == 0) {
 				motor[motorA] = 0;
 				motor[motorB] = 0;
 				motor[motorC] = 0;
 				motor[motorD] = 0;
 				movefoward = false;
 			}
 			else if (movex == 5) {
 				motor[motorA] = movey - 1;
 				motor[motorB] = -movey - 1;
 				motor[motorC] = movement[movex] + 10;
 				motor[motorD] = movement[movex];
 			}
 			else {
 				motor[motorC] = movement[movex] + 10;
 				motor[motorD] = movement[movex];
 			}
 		}
  }
}
